name = "OptTestFunctions"
uuid = "a3783753-87a8-4d47-a5de-3f6cbdd8a78d"
authors = ["Emanuel Queiroz, Samara Vilar, Giselle Lopes, Marcio Bortoloti"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
